sudo:       required
language:   generic
services:   docker

# Docs of the options: https://github.com/Strauman/travis-latexbuild/tree/master#configuration-options
tex-config:
  - tex-scheme=small
  - push-type=none
  - build-pattern=src/main.tex,src/mwe.tex
  - latexmk-flags=
  # Check at https://www.ctan.org/pkg/package-name in which TeX Live package a LaTeX package is contained.
  - packages=collection-langeuropean

script:
  # This requires uploading username and a token as Travis environment variables
  - docker login -u $GH_REGISTRY_USERNAME -p $GH_REGISTRY_TOKEN docker.pkg.github.com
  - docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind docker.pkg.github.com/strauman/travis-latexbuild/texlive-latexbuild:texliveonfly-2019
