sudo:       required
services:   docker

script:
- docker pull strauman/travis-latexbuild:small # small texlive scheme
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:small # also here