language: generic

# Dependency of the minted package
#before_install:
# - sudo apt-get install python-pygments
install:
 - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
# Change working directory so including files will work
before_script: cd $TRAVIS_BUILD_DIR/src/
script:
# texliveonfly will download packages automatically, use latexmk to automatically handle bibtex and references
- texliveonfly --compiler=latexmk --arguments="-pdf" ./fonts-test.tex
