jobs:
  include:
#    - stage: install
    - script: ls -la
    - script: chmod +x ./texlive_install.sh
    - script: ./texlive_install.sh
#    - stage: compile
#      script: ./2-texlive-pdflatex/compile.sh