before_install:
- sudo apt-get update 
- sudo apt-get install texlive-latex-extra
script:
- mkdir _build
- pdflatex -output-directory _build ./src/main.tex
deploy:
  provider: releases
  file:
  - ./_build/main.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master