sudo: required
language: generic
services: docker

tex-config:
  - build-pattern=src/reitzig.tex
  - packages=adjustbox,fontenc,geometry,ifpdf,ifxetex,ifluatex,pdfpages,qrcode,relsize,tikz,xifthen,xparse,yfonts

script:
  - docker run --mount src=${TRAVIS_BUILD_DIR}/,target=/repo,type=bind phpirates/texlive-latexbuild:texliveonfly