sudo: required
language: generic
services: docker
script:
- docker pull dxjoke/tectonic-docker:personal
- docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic --keep-intermediates --reruns 0 biber-mwe.tex; biber biber-mwe;
  tectonic biber-mwe.tex; tectonic main.tex"
deploy:
  provider: releases
  api_key:
    secure: BbXIQxnNO10t196betzxKEg+bli8atpIzT8Q6R12+1E2wyEfY2rK6UXG1i850N1V7BsECurtWLelzHr9PkYxHT5rSDeZ1OY9+6xZw+zvQXq0itxg+H0OGqlAKCNiPuKEhnzbFSE0LEyheGXmOqfsKvhfjqnP0V8hCuWyI5BMfURrXXcDvwkR0pjudIJaKsYXvR03WNdRSFDfaujdEFseH7LaWtgN4jDTGXLhN7jSElYU+613cj1xSSNTNMA77c7BZRx88YqF0fRbQ4YIhS1j05XpRvJ+uwkcwOH0UsIPF/ZQlB+KsTLkCVQ6EAfZl/l6Qqwrp+gIFmhTKHIx6BSGV64nJ6W0UR7vji6eG5SuNH6Km0JimHKh2P09NedgxJTlYT3jgJL62V2QcqP69KOO+lexIiO4Xt/uQe0BalFlQlDkozJf+vPRMokz29HJRBeYqtXpYI0vD/Nw1Eg1mgLTMtbnqu5iovnWFAQBotAyb5NAbOw+W3nEune3wsIzeMdeAlP6EU/HSanuINw9DqUYoEmliTqlxcQcaJ2kENSrFJ6/BJ2VNpPNJ7lG6z1mZC7HfM6NSsXnwrSFjzZRuEgQp1vCc0pK8/QCvqlmv6DBWxCtV+9W6+DsokwsDSapXz5J+NdLWGSO9sxVX1fVtgeDp5UM6yfyywh7BQTf3GZjhWg=
  file:
  - ./src/biber-mwe.pdf
  - ./src/main.pdf
  
  on:
    repo: WtfJoke/travis-ci-latex-pdf
