jobs:
  include:
#    - stage: install
    - script: ls -la
    - script: chmod +x 2texlivepfdlatex/texlive_install.sh && 2texlivepfdlatex/texlive_install.sh
#    - stage: compile
#      script: ./2-texlive-pdflatex/compile.sh