language: generic
before_install:
- sudo apt-get install texlive-binaries
- chmod +x .travis/git-info-2.sh
- ".travis/git-info-2.sh"
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- if ! command -v conda > /dev/null; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda -u; conda config --add
  channels conda-forge; conda config --set always_yes yes; conda install tectonic==0.1.11;
  fi
- conda install -c malramsay biber==2.11 --yes
- conda info -a
cache:
  directories:
  - "$HOME/miniconda"
  - "$HOME/.cache/Tectonic"
script:
- cd ./src/
- tectonic --keep-intermediates --print ./git-info-2-mwe.tex
- cd ../
deploy:
  provider: releases
  api_key:
    secure: GME/XOMyuXmenPgM1l1lKfZuIbagmEtRSPULXhqu2NbQoqgDlAreIA6NkQv0KiU+e+MBb1XHHnh25X92xUQ1xr8lb52GHhgdCsc4Le17ymqxjPbPb446En+NGpd3Kia4cie4sDfumDsDxiHtVB9qCtUF78ja+PmFYgZkTOJC2QMOVF0EM9KLR5On9d+sklE1yMXHe3Ex4q71YKg7XechbEU85QqYZzTkgr5CZd1XKWA3vN0BrRJCDXR4ivsMmVl4osI6GkSrm86tr++rK7Eg4wZHavtRDeWwU5m0/9KYxeCNANfjjPcKMZBhl05Q3EVEeqZ2dUS15BJoXM5Rs7MznnWidPw09dJcHTGXTwQ6LDfdVYRfoWwrN4/ERIWMKH9+T9As1ydpIta/HLcOwb8t5mLiP61njBd4leOPyWreg8BOLskFLViC3M0naZIYtdSMfV/+F8+OCun5IeytDeclvLu6HAv31LLlWhSh1tksoPY9cg26Oo9a6/FuY+Ighavo8D2fxbv/Xulv1pCdROr6V8exunAIPIvDVHG4mTPVYIXLIdtmdJn8xdcPCzd22dOgiD2Bqxfd3ZmZCTFgF2voarYbrIRMfXBnlAhzRHNQNTpDiU49swRYP1oXlXZXG+0TXo7goMGhjq2BX3oT1K77oqP/i5+Z45uk9AfI+4hALAs=
  file:
    - ./src/git-info-2-mwe.pdf
  skip_cleanup: true
  on:
    repo: PHPirates/travis-ci-latex-pdf
    branch: gitinfo2
