name: Github Action for LaTeX by xu-cheng

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Compile main.tex
        uses: xu-cheng/latex-action@master
        with:
          # The root LaTeX file to be compiled
          root_file: main.tex
          # The working directory for the LaTeX engine
          working_directory: src/
          # The LaTeX engine to be invoked
#          compiler: # optional, default is latexmk
          # Extra arguments to be passed to the LaTeX engine
#          args: # optional, default is -pdf -file-line-error -interaction=nonstopmode
          # Install extra packages by apk
#          extra_system_packages: # optional
      - name: Compile biber-mwe.tex
        uses: xu-cheng/latex-action@master
        with:
          root_file: biber-mwe.tex
          working_directory: src/
      - name: Compile minted.tex
        uses: xu-cheng/latex-action@master
        with:
          root_file: minted.tex
          working_directory: src/
          args: -pdf -file-line-error -interaction=nonstopmode -shell-escape
      - run: mkdir $HOME/.fonts
      - run: cp -a src/fonts/. $HOME/.fonts/
      - run: fc-cache -f -v
      - name: Compile fonts.tex
        uses: xu-cheng/latex-action@master
        with:
          root_file: fonts.tex
          working_directory: src/
          args: -xelatex -file-line-error -interaction=nonstopmode
      - name: Upload pdfs
        uses: actions/upload-artifact@v1
        with:
          name: main.pdf
          path: src/main.pdf
